name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        elixir-otp:
          # quote version numbers so they don't get parsed as numbers
          # 1.10 would be converted to 1.1
          # see: https://bobs-list.kobrakai.de
          - elixir: "1.10"
            otp: 22
          - elixir: "1.10"
            otp: 21
          - elixir: "1.9"
            otp: 20
          - elixir: "1.8"
            otp: 20
          - elixir: "1.7"
            otp: 19

    steps:
      - uses: actions/checkout@v2

      - name: Setup Elixir ${{ matrix.elixir-otp.elixir }} OTP ${{ matrix.elixir-otp.otp }}
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.elixir-otp.otp }}
          elixir-version: ${{ matrix.elixir-otp.elixir }}

      - name: dep cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - run: mix deps.get --only $MIX_ENV

      - run: mix test
